dir: '{{.InterfaceDirRelative}}'
template: testify
template-data:
  mock-build-tags: '!release'
  unroll-variadic: true
packages:
  github.com/gemyago/atlacp/internal/api/mcp/controllers:
    interfaces:
      bitbucketService:
  github.com/gemyago/atlacp/internal/app:
    interfaces:
      AtlassianAccountsRepository:
      bitbucketAuthFactory:
      bitbucketClient:
  log/slog:
    interfaces:
      Handler:
        config:
          dir: internal/diag
          structname: MockSlogHandler
          pkgname: diag
