dir: "{{.InterfaceDirRelative}}"
inpackage: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mock-build-tags: "!release"
disable-version-string: true
packages:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'internal/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler
  github.com/gemyago/atlacp/internal/app:
    interfaces:
      bitbucketAuthFactory:
      BitbucketClient:
      AtlassianAccountsRepository:
  github.com/gemyago/atlacp/internal/api/mcp/controllers:
    interfaces:
      bitbucketService: