// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	bitbucket "github.com/gemyago/atlacp/internal/services/bitbucket"

	mock "github.com/stretchr/testify/mock"
)

// MockbitbucketClient is an autogenerated mock type for the bitbucketClient type
type MockbitbucketClient struct {
	mock.Mock
}

type MockbitbucketClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockbitbucketClient) EXPECT() *MockbitbucketClient_Expecter {
	return &MockbitbucketClient_Expecter{mock: &_m.Mock}
}

// ApprovePR provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) ApprovePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ApprovePRParams) (*bitbucket.Participant, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for ApprovePR")
	}

	var r0 *bitbucket.Participant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ApprovePRParams) (*bitbucket.Participant, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ApprovePRParams) *bitbucket.Participant); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.Participant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.ApprovePRParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_ApprovePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApprovePR'
type MockbitbucketClient_ApprovePR_Call struct {
	*mock.Call
}

// ApprovePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.ApprovePRParams
func (_e *MockbitbucketClient_Expecter) ApprovePR(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_ApprovePR_Call {
	return &MockbitbucketClient_ApprovePR_Call{Call: _e.mock.On("ApprovePR", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_ApprovePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ApprovePRParams)) *MockbitbucketClient_ApprovePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.ApprovePRParams))
	})
	return _c
}

func (_c *MockbitbucketClient_ApprovePR_Call) Return(_a0 *bitbucket.Participant, _a1 error) *MockbitbucketClient_ApprovePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_ApprovePR_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.ApprovePRParams) (*bitbucket.Participant, error)) *MockbitbucketClient_ApprovePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) CreatePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePRParams) (*bitbucket.PullRequest, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePRParams) (*bitbucket.PullRequest, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePRParams) *bitbucket.PullRequest); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePRParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockbitbucketClient_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.CreatePRParams
func (_e *MockbitbucketClient_Expecter) CreatePR(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_CreatePR_Call {
	return &MockbitbucketClient_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_CreatePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePRParams)) *MockbitbucketClient_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.CreatePRParams))
	})
	return _c
}

func (_c *MockbitbucketClient_CreatePR_Call) Return(_a0 *bitbucket.PullRequest, _a1 error) *MockbitbucketClient_CreatePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_CreatePR_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePRParams) (*bitbucket.PullRequest, error)) *MockbitbucketClient_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequestTask provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) CreatePullRequestTask(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePullRequestTaskParams) (*bitbucket.PullRequestCommentTask, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequestTask")
	}

	var r0 *bitbucket.PullRequestCommentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePullRequestTaskParams) (*bitbucket.PullRequestCommentTask, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePullRequestTaskParams) *bitbucket.PullRequestCommentTask); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequestCommentTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePullRequestTaskParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_CreatePullRequestTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequestTask'
type MockbitbucketClient_CreatePullRequestTask_Call struct {
	*mock.Call
}

// CreatePullRequestTask is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.CreatePullRequestTaskParams
func (_e *MockbitbucketClient_Expecter) CreatePullRequestTask(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_CreatePullRequestTask_Call {
	return &MockbitbucketClient_CreatePullRequestTask_Call{Call: _e.mock.On("CreatePullRequestTask", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_CreatePullRequestTask_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePullRequestTaskParams)) *MockbitbucketClient_CreatePullRequestTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.CreatePullRequestTaskParams))
	})
	return _c
}

func (_c *MockbitbucketClient_CreatePullRequestTask_Call) Return(_a0 *bitbucket.PullRequestCommentTask, _a1 error) *MockbitbucketClient_CreatePullRequestTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_CreatePullRequestTask_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePullRequestTaskParams) (*bitbucket.PullRequestCommentTask, error)) *MockbitbucketClient_CreatePullRequestTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetPR provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) GetPR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRParams) (*bitbucket.PullRequest, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRParams) (*bitbucket.PullRequest, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRParams) *bitbucket.PullRequest); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_GetPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPR'
type MockbitbucketClient_GetPR_Call struct {
	*mock.Call
}

// GetPR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.GetPRParams
func (_e *MockbitbucketClient_Expecter) GetPR(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_GetPR_Call {
	return &MockbitbucketClient_GetPR_Call{Call: _e.mock.On("GetPR", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_GetPR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRParams)) *MockbitbucketClient_GetPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.GetPRParams))
	})
	return _c
}

func (_c *MockbitbucketClient_GetPR_Call) Return(_a0 *bitbucket.PullRequest, _a1 error) *MockbitbucketClient_GetPR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_GetPR_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRParams) (*bitbucket.PullRequest, error)) *MockbitbucketClient_GetPR_Call {
	_c.Call.Return(run)
	return _c
}

// ListPullRequestTasks provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) ListPullRequestTasks(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPullRequestTasksParams) (*bitbucket.PaginatedTasks, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPullRequestTasks")
	}

	var r0 *bitbucket.PaginatedTasks
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPullRequestTasksParams) (*bitbucket.PaginatedTasks, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPullRequestTasksParams) *bitbucket.PaginatedTasks); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PaginatedTasks)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPullRequestTasksParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_ListPullRequestTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPullRequestTasks'
type MockbitbucketClient_ListPullRequestTasks_Call struct {
	*mock.Call
}

// ListPullRequestTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.ListPullRequestTasksParams
func (_e *MockbitbucketClient_Expecter) ListPullRequestTasks(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_ListPullRequestTasks_Call {
	return &MockbitbucketClient_ListPullRequestTasks_Call{Call: _e.mock.On("ListPullRequestTasks", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_ListPullRequestTasks_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPullRequestTasksParams)) *MockbitbucketClient_ListPullRequestTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.ListPullRequestTasksParams))
	})
	return _c
}

func (_c *MockbitbucketClient_ListPullRequestTasks_Call) Return(_a0 *bitbucket.PaginatedTasks, _a1 error) *MockbitbucketClient_ListPullRequestTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_ListPullRequestTasks_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.ListPullRequestTasksParams) (*bitbucket.PaginatedTasks, error)) *MockbitbucketClient_ListPullRequestTasks_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) MergePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.MergePRParams) (*bitbucket.PullRequest, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.MergePRParams) (*bitbucket.PullRequest, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.MergePRParams) *bitbucket.PullRequest); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.MergePRParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type MockbitbucketClient_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.MergePRParams
func (_e *MockbitbucketClient_Expecter) MergePR(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_MergePR_Call {
	return &MockbitbucketClient_MergePR_Call{Call: _e.mock.On("MergePR", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_MergePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.MergePRParams)) *MockbitbucketClient_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.MergePRParams))
	})
	return _c
}

func (_c *MockbitbucketClient_MergePR_Call) Return(_a0 *bitbucket.PullRequest, _a1 error) *MockbitbucketClient_MergePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_MergePR_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.MergePRParams) (*bitbucket.PullRequest, error)) *MockbitbucketClient_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePR provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) UpdatePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdatePRParams) (*bitbucket.PullRequest, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdatePRParams) (*bitbucket.PullRequest, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdatePRParams) *bitbucket.PullRequest); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdatePRParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_UpdatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePR'
type MockbitbucketClient_UpdatePR_Call struct {
	*mock.Call
}

// UpdatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.UpdatePRParams
func (_e *MockbitbucketClient_Expecter) UpdatePR(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_UpdatePR_Call {
	return &MockbitbucketClient_UpdatePR_Call{Call: _e.mock.On("UpdatePR", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_UpdatePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdatePRParams)) *MockbitbucketClient_UpdatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.UpdatePRParams))
	})
	return _c
}

func (_c *MockbitbucketClient_UpdatePR_Call) Return(_a0 *bitbucket.PullRequest, _a1 error) *MockbitbucketClient_UpdatePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_UpdatePR_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.UpdatePRParams) (*bitbucket.PullRequest, error)) *MockbitbucketClient_UpdatePR_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, tokenProvider, params
func (_m *MockbitbucketClient) UpdateTask(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdateTaskParams) (*bitbucket.PullRequestCommentTask, error) {
	ret := _m.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *bitbucket.PullRequestCommentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdateTaskParams) (*bitbucket.PullRequestCommentTask, error)); ok {
		return rf(ctx, tokenProvider, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdateTaskParams) *bitbucket.PullRequestCommentTask); ok {
		r0 = rf(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequestCommentTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdateTaskParams) error); ok {
		r1 = rf(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockbitbucketClient_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockbitbucketClient_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.UpdateTaskParams
func (_e *MockbitbucketClient_Expecter) UpdateTask(ctx interface{}, tokenProvider interface{}, params interface{}) *MockbitbucketClient_UpdateTask_Call {
	return &MockbitbucketClient_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, tokenProvider, params)}
}

func (_c *MockbitbucketClient_UpdateTask_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdateTaskParams)) *MockbitbucketClient_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bitbucket.TokenProvider), args[2].(bitbucket.UpdateTaskParams))
	})
	return _c
}

func (_c *MockbitbucketClient_UpdateTask_Call) Return(_a0 *bitbucket.PullRequestCommentTask, _a1 error) *MockbitbucketClient_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockbitbucketClient_UpdateTask_Call) RunAndReturn(run func(context.Context, bitbucket.TokenProvider, bitbucket.UpdateTaskParams) (*bitbucket.PullRequestCommentTask, error)) *MockbitbucketClient_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbitbucketClient creates a new instance of MockbitbucketClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbitbucketClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockbitbucketClient {
	mock := &MockbitbucketClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
