// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package app

import (
	"context"
	"time"

	"github.com/gemyago/atlacp/internal/services/bitbucket"
	mock "github.com/stretchr/testify/mock"
)

// newMockbitbucketAuthFactory creates a new instance of mockbitbucketAuthFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbitbucketAuthFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbitbucketAuthFactory {
	mock := &mockbitbucketAuthFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbitbucketAuthFactory is an autogenerated mock type for the bitbucketAuthFactory type
type mockbitbucketAuthFactory struct {
	mock.Mock
}

type mockbitbucketAuthFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbitbucketAuthFactory) EXPECT() *mockbitbucketAuthFactory_Expecter {
	return &mockbitbucketAuthFactory_Expecter{mock: &_m.Mock}
}

// getTokenProvider provides a mock function for the type mockbitbucketAuthFactory
func (_mock *mockbitbucketAuthFactory) getTokenProvider(ctx context.Context, accountName string) tokenProviderFunc {
	ret := _mock.Called(ctx, accountName)

	if len(ret) == 0 {
		panic("no return value specified for getTokenProvider")
	}

	var r0 tokenProviderFunc
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) tokenProviderFunc); ok {
		r0 = returnFunc(ctx, accountName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tokenProviderFunc)
		}
	}
	return r0
}

// mockbitbucketAuthFactory_getTokenProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getTokenProvider'
type mockbitbucketAuthFactory_getTokenProvider_Call struct {
	*mock.Call
}

// getTokenProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - accountName string
func (_e *mockbitbucketAuthFactory_Expecter) getTokenProvider(ctx interface{}, accountName interface{}) *mockbitbucketAuthFactory_getTokenProvider_Call {
	return &mockbitbucketAuthFactory_getTokenProvider_Call{Call: _e.mock.On("getTokenProvider", ctx, accountName)}
}

func (_c *mockbitbucketAuthFactory_getTokenProvider_Call) Run(run func(ctx context.Context, accountName string)) *mockbitbucketAuthFactory_getTokenProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketAuthFactory_getTokenProvider_Call) Return(tokenProviderFuncMoqParam tokenProviderFunc) *mockbitbucketAuthFactory_getTokenProvider_Call {
	_c.Call.Return(tokenProviderFuncMoqParam)
	return _c
}

func (_c *mockbitbucketAuthFactory_getTokenProvider_Call) RunAndReturn(run func(ctx context.Context, accountName string) tokenProviderFunc) *mockbitbucketAuthFactory_getTokenProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAtlassianAccountsRepository creates a new instance of MockAtlassianAccountsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAtlassianAccountsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAtlassianAccountsRepository {
	mock := &MockAtlassianAccountsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAtlassianAccountsRepository is an autogenerated mock type for the AtlassianAccountsRepository type
type MockAtlassianAccountsRepository struct {
	mock.Mock
}

type MockAtlassianAccountsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAtlassianAccountsRepository) EXPECT() *MockAtlassianAccountsRepository_Expecter {
	return &MockAtlassianAccountsRepository_Expecter{mock: &_m.Mock}
}

// GetAccountByName provides a mock function for the type MockAtlassianAccountsRepository
func (_mock *MockAtlassianAccountsRepository) GetAccountByName(ctx context.Context, name string) (*AtlassianAccount, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByName")
	}

	var r0 *AtlassianAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*AtlassianAccount, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *AtlassianAccount); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AtlassianAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAtlassianAccountsRepository_GetAccountByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByName'
type MockAtlassianAccountsRepository_GetAccountByName_Call struct {
	*mock.Call
}

// GetAccountByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAtlassianAccountsRepository_Expecter) GetAccountByName(ctx interface{}, name interface{}) *MockAtlassianAccountsRepository_GetAccountByName_Call {
	return &MockAtlassianAccountsRepository_GetAccountByName_Call{Call: _e.mock.On("GetAccountByName", ctx, name)}
}

func (_c *MockAtlassianAccountsRepository_GetAccountByName_Call) Run(run func(ctx context.Context, name string)) *MockAtlassianAccountsRepository_GetAccountByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAtlassianAccountsRepository_GetAccountByName_Call) Return(atlassianAccount *AtlassianAccount, err error) *MockAtlassianAccountsRepository_GetAccountByName_Call {
	_c.Call.Return(atlassianAccount, err)
	return _c
}

func (_c *MockAtlassianAccountsRepository_GetAccountByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*AtlassianAccount, error)) *MockAtlassianAccountsRepository_GetAccountByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultAccount provides a mock function for the type MockAtlassianAccountsRepository
func (_mock *MockAtlassianAccountsRepository) GetDefaultAccount(ctx context.Context) (*AtlassianAccount, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultAccount")
	}

	var r0 *AtlassianAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*AtlassianAccount, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *AtlassianAccount); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AtlassianAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAtlassianAccountsRepository_GetDefaultAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultAccount'
type MockAtlassianAccountsRepository_GetDefaultAccount_Call struct {
	*mock.Call
}

// GetDefaultAccount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAtlassianAccountsRepository_Expecter) GetDefaultAccount(ctx interface{}) *MockAtlassianAccountsRepository_GetDefaultAccount_Call {
	return &MockAtlassianAccountsRepository_GetDefaultAccount_Call{Call: _e.mock.On("GetDefaultAccount", ctx)}
}

func (_c *MockAtlassianAccountsRepository_GetDefaultAccount_Call) Run(run func(ctx context.Context)) *MockAtlassianAccountsRepository_GetDefaultAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAtlassianAccountsRepository_GetDefaultAccount_Call) Return(atlassianAccount *AtlassianAccount, err error) *MockAtlassianAccountsRepository_GetDefaultAccount_Call {
	_c.Call.Return(atlassianAccount, err)
	return _c
}

func (_c *MockAtlassianAccountsRepository_GetDefaultAccount_Call) RunAndReturn(run func(ctx context.Context) (*AtlassianAccount, error)) *MockAtlassianAccountsRepository_GetDefaultAccount_Call {
	_c.Call.Return(run)
	return _c
}

// newMockbitbucketClient creates a new instance of mockbitbucketClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbitbucketClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbitbucketClient {
	mock := &mockbitbucketClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbitbucketClient is an autogenerated mock type for the bitbucketClient type
type mockbitbucketClient struct {
	mock.Mock
}

type mockbitbucketClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbitbucketClient) EXPECT() *mockbitbucketClient_Expecter {
	return &mockbitbucketClient_Expecter{mock: &_m.Mock}
}

// AddPRComment provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) AddPRComment(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.AddPRCommentParams) (int64, string, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for AddPRComment")
	}

	var r0 int64
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.AddPRCommentParams) (int64, string, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.AddPRCommentParams) int64); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.AddPRCommentParams) string); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, bitbucket.TokenProvider, bitbucket.AddPRCommentParams) error); ok {
		r2 = returnFunc(ctx, tokenProvider, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockbitbucketClient_AddPRComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPRComment'
type mockbitbucketClient_AddPRComment_Call struct {
	*mock.Call
}

// AddPRComment is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.AddPRCommentParams
func (_e *mockbitbucketClient_Expecter) AddPRComment(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_AddPRComment_Call {
	return &mockbitbucketClient_AddPRComment_Call{Call: _e.mock.On("AddPRComment", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_AddPRComment_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.AddPRCommentParams)) *mockbitbucketClient_AddPRComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.AddPRCommentParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.AddPRCommentParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_AddPRComment_Call) Return(n int64, s string, err error) *mockbitbucketClient_AddPRComment_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *mockbitbucketClient_AddPRComment_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.AddPRCommentParams) (int64, string, error)) *mockbitbucketClient_AddPRComment_Call {
	_c.Call.Return(run)
	return _c
}

// ApprovePR provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) ApprovePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ApprovePRParams) (*bitbucket.Participant, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for ApprovePR")
	}

	var r0 *bitbucket.Participant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ApprovePRParams) (*bitbucket.Participant, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ApprovePRParams) *bitbucket.Participant); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.Participant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.ApprovePRParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_ApprovePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApprovePR'
type mockbitbucketClient_ApprovePR_Call struct {
	*mock.Call
}

// ApprovePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.ApprovePRParams
func (_e *mockbitbucketClient_Expecter) ApprovePR(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_ApprovePR_Call {
	return &mockbitbucketClient_ApprovePR_Call{Call: _e.mock.On("ApprovePR", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_ApprovePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ApprovePRParams)) *mockbitbucketClient_ApprovePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.ApprovePRParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.ApprovePRParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_ApprovePR_Call) Return(participant *bitbucket.Participant, err error) *mockbitbucketClient_ApprovePR_Call {
	_c.Call.Return(participant, err)
	return _c
}

func (_c *mockbitbucketClient_ApprovePR_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ApprovePRParams) (*bitbucket.Participant, error)) *mockbitbucketClient_ApprovePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) CreatePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePRParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type mockbitbucketClient_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.CreatePRParams
func (_e *mockbitbucketClient_Expecter) CreatePR(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_CreatePR_Call {
	return &mockbitbucketClient_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_CreatePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePRParams)) *mockbitbucketClient_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.CreatePRParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.CreatePRParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_CreatePR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketClient_CreatePR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketClient_CreatePR_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePRParams) (*bitbucket.PullRequest, error)) *mockbitbucketClient_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequestTask provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) CreatePullRequestTask(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePullRequestTaskParams) (*bitbucket.PullRequestCommentTask, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequestTask")
	}

	var r0 *bitbucket.PullRequestCommentTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePullRequestTaskParams) (*bitbucket.PullRequestCommentTask, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePullRequestTaskParams) *bitbucket.PullRequestCommentTask); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequestCommentTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.CreatePullRequestTaskParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_CreatePullRequestTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequestTask'
type mockbitbucketClient_CreatePullRequestTask_Call struct {
	*mock.Call
}

// CreatePullRequestTask is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.CreatePullRequestTaskParams
func (_e *mockbitbucketClient_Expecter) CreatePullRequestTask(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_CreatePullRequestTask_Call {
	return &mockbitbucketClient_CreatePullRequestTask_Call{Call: _e.mock.On("CreatePullRequestTask", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_CreatePullRequestTask_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePullRequestTaskParams)) *mockbitbucketClient_CreatePullRequestTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.CreatePullRequestTaskParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.CreatePullRequestTaskParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_CreatePullRequestTask_Call) Return(pullRequestCommentTask *bitbucket.PullRequestCommentTask, err error) *mockbitbucketClient_CreatePullRequestTask_Call {
	_c.Call.Return(pullRequestCommentTask, err)
	return _c
}

func (_c *mockbitbucketClient_CreatePullRequestTask_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.CreatePullRequestTaskParams) (*bitbucket.PullRequestCommentTask, error)) *mockbitbucketClient_CreatePullRequestTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileContent provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) GetFileContent(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetFileContentParams) (*bitbucket.FileContent, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContent")
	}

	var r0 *bitbucket.FileContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetFileContentParams) (*bitbucket.FileContent, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetFileContentParams) *bitbucket.FileContent); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.FileContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetFileContentParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_GetFileContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileContent'
type mockbitbucketClient_GetFileContent_Call struct {
	*mock.Call
}

// GetFileContent is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.GetFileContentParams
func (_e *mockbitbucketClient_Expecter) GetFileContent(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_GetFileContent_Call {
	return &mockbitbucketClient_GetFileContent_Call{Call: _e.mock.On("GetFileContent", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_GetFileContent_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetFileContentParams)) *mockbitbucketClient_GetFileContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.GetFileContentParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.GetFileContentParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_GetFileContent_Call) Return(fileContent *bitbucket.FileContent, err error) *mockbitbucketClient_GetFileContent_Call {
	_c.Call.Return(fileContent, err)
	return _c
}

func (_c *mockbitbucketClient_GetFileContent_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetFileContentParams) (*bitbucket.FileContent, error)) *mockbitbucketClient_GetFileContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetPR provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) GetPR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_GetPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPR'
type mockbitbucketClient_GetPR_Call struct {
	*mock.Call
}

// GetPR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.GetPRParams
func (_e *mockbitbucketClient_Expecter) GetPR(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_GetPR_Call {
	return &mockbitbucketClient_GetPR_Call{Call: _e.mock.On("GetPR", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_GetPR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRParams)) *mockbitbucketClient_GetPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.GetPRParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.GetPRParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_GetPR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketClient_GetPR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketClient_GetPR_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRParams) (*bitbucket.PullRequest, error)) *mockbitbucketClient_GetPR_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRDiff provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) GetPRDiff(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRDiffParams) (string, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPRDiff")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRDiffParams) (string, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRDiffParams) string); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRDiffParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_GetPRDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRDiff'
type mockbitbucketClient_GetPRDiff_Call struct {
	*mock.Call
}

// GetPRDiff is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.GetPRDiffParams
func (_e *mockbitbucketClient_Expecter) GetPRDiff(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_GetPRDiff_Call {
	return &mockbitbucketClient_GetPRDiff_Call{Call: _e.mock.On("GetPRDiff", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_GetPRDiff_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRDiffParams)) *mockbitbucketClient_GetPRDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.GetPRDiffParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.GetPRDiffParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_GetPRDiff_Call) Return(s string, err error) *mockbitbucketClient_GetPRDiff_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockbitbucketClient_GetPRDiff_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRDiffParams) (string, error)) *mockbitbucketClient_GetPRDiff_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRDiffStat provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) GetPRDiffStat(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRDiffStatParams) (*struct {
	Size    int                  "json:\"size,omitempty\""
	Page    int                  "json:\"page,omitempty\""
	PageLen int                  "json:\"pagelen,omitempty\""
	Values  []bitbucket.DiffStat "json:\"values\""
}, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPRDiffStat")
	}

	var r0 *struct {
		Size    int                  "json:\"size,omitempty\""
		Page    int                  "json:\"page,omitempty\""
		PageLen int                  "json:\"pagelen,omitempty\""
		Values  []bitbucket.DiffStat "json:\"values\""
	}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRDiffStatParams) (*struct {
		Size    int                  "json:\"size,omitempty\""
		Page    int                  "json:\"page,omitempty\""
		PageLen int                  "json:\"pagelen,omitempty\""
		Values  []bitbucket.DiffStat "json:\"values\""
	}, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRDiffStatParams) *struct {
		Size    int                  "json:\"size,omitempty\""
		Page    int                  "json:\"page,omitempty\""
		PageLen int                  "json:\"pagelen,omitempty\""
		Values  []bitbucket.DiffStat "json:\"values\""
	}); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*struct {
				Size    int                  "json:\"size,omitempty\""
				Page    int                  "json:\"page,omitempty\""
				PageLen int                  "json:\"pagelen,omitempty\""
				Values  []bitbucket.DiffStat "json:\"values\""
			})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.GetPRDiffStatParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_GetPRDiffStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRDiffStat'
type mockbitbucketClient_GetPRDiffStat_Call struct {
	*mock.Call
}

// GetPRDiffStat is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.GetPRDiffStatParams
func (_e *mockbitbucketClient_Expecter) GetPRDiffStat(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_GetPRDiffStat_Call {
	return &mockbitbucketClient_GetPRDiffStat_Call{Call: _e.mock.On("GetPRDiffStat", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_GetPRDiffStat_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRDiffStatParams)) *mockbitbucketClient_GetPRDiffStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.GetPRDiffStatParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.GetPRDiffStatParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_GetPRDiffStat_Call) Return(val *struct {
	Size    int                  "json:\"size,omitempty\""
	Page    int                  "json:\"page,omitempty\""
	PageLen int                  "json:\"pagelen,omitempty\""
	Values  []bitbucket.DiffStat "json:\"values\""
}, err error) *mockbitbucketClient_GetPRDiffStat_Call {
	_c.Call.Return(val, err)
	return _c
}

func (_c *mockbitbucketClient_GetPRDiffStat_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.GetPRDiffStatParams) (*struct {
	Size    int                  "json:\"size,omitempty\""
	Page    int                  "json:\"page,omitempty\""
	PageLen int                  "json:\"pagelen,omitempty\""
	Values  []bitbucket.DiffStat "json:\"values\""
}, error)) *mockbitbucketClient_GetPRDiffStat_Call {
	_c.Call.Return(run)
	return _c
}

// ListPRComments provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) ListPRComments(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPRCommentsParams) (*bitbucket.ListPRCommentsResponse, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPRComments")
	}

	var r0 *bitbucket.ListPRCommentsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPRCommentsParams) (*bitbucket.ListPRCommentsResponse, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPRCommentsParams) *bitbucket.ListPRCommentsResponse); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.ListPRCommentsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPRCommentsParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_ListPRComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPRComments'
type mockbitbucketClient_ListPRComments_Call struct {
	*mock.Call
}

// ListPRComments is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.ListPRCommentsParams
func (_e *mockbitbucketClient_Expecter) ListPRComments(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_ListPRComments_Call {
	return &mockbitbucketClient_ListPRComments_Call{Call: _e.mock.On("ListPRComments", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_ListPRComments_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPRCommentsParams)) *mockbitbucketClient_ListPRComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.ListPRCommentsParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.ListPRCommentsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_ListPRComments_Call) Return(listPRCommentsResponse *bitbucket.ListPRCommentsResponse, err error) *mockbitbucketClient_ListPRComments_Call {
	_c.Call.Return(listPRCommentsResponse, err)
	return _c
}

func (_c *mockbitbucketClient_ListPRComments_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPRCommentsParams) (*bitbucket.ListPRCommentsResponse, error)) *mockbitbucketClient_ListPRComments_Call {
	_c.Call.Return(run)
	return _c
}

// ListPullRequestTasks provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) ListPullRequestTasks(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPullRequestTasksParams) (*bitbucket.PaginatedTasks, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPullRequestTasks")
	}

	var r0 *bitbucket.PaginatedTasks
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPullRequestTasksParams) (*bitbucket.PaginatedTasks, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPullRequestTasksParams) *bitbucket.PaginatedTasks); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PaginatedTasks)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.ListPullRequestTasksParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_ListPullRequestTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPullRequestTasks'
type mockbitbucketClient_ListPullRequestTasks_Call struct {
	*mock.Call
}

// ListPullRequestTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.ListPullRequestTasksParams
func (_e *mockbitbucketClient_Expecter) ListPullRequestTasks(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_ListPullRequestTasks_Call {
	return &mockbitbucketClient_ListPullRequestTasks_Call{Call: _e.mock.On("ListPullRequestTasks", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_ListPullRequestTasks_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPullRequestTasksParams)) *mockbitbucketClient_ListPullRequestTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.ListPullRequestTasksParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.ListPullRequestTasksParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_ListPullRequestTasks_Call) Return(paginatedTasks *bitbucket.PaginatedTasks, err error) *mockbitbucketClient_ListPullRequestTasks_Call {
	_c.Call.Return(paginatedTasks, err)
	return _c
}

func (_c *mockbitbucketClient_ListPullRequestTasks_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ListPullRequestTasksParams) (*bitbucket.PaginatedTasks, error)) *mockbitbucketClient_ListPullRequestTasks_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) MergePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.MergePRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.MergePRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.MergePRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.MergePRParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type mockbitbucketClient_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.MergePRParams
func (_e *mockbitbucketClient_Expecter) MergePR(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_MergePR_Call {
	return &mockbitbucketClient_MergePR_Call{Call: _e.mock.On("MergePR", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_MergePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.MergePRParams)) *mockbitbucketClient_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.MergePRParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.MergePRParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_MergePR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketClient_MergePR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketClient_MergePR_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.MergePRParams) (*bitbucket.PullRequest, error)) *mockbitbucketClient_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPRChanges provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) RequestPRChanges(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.RequestPRChangesParams) (string, time.Time, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for RequestPRChanges")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.RequestPRChangesParams) (string, time.Time, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.RequestPRChangesParams) string); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.RequestPRChangesParams) time.Time); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, bitbucket.TokenProvider, bitbucket.RequestPRChangesParams) error); ok {
		r2 = returnFunc(ctx, tokenProvider, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockbitbucketClient_RequestPRChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPRChanges'
type mockbitbucketClient_RequestPRChanges_Call struct {
	*mock.Call
}

// RequestPRChanges is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.RequestPRChangesParams
func (_e *mockbitbucketClient_Expecter) RequestPRChanges(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_RequestPRChanges_Call {
	return &mockbitbucketClient_RequestPRChanges_Call{Call: _e.mock.On("RequestPRChanges", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_RequestPRChanges_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.RequestPRChangesParams)) *mockbitbucketClient_RequestPRChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.RequestPRChangesParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.RequestPRChangesParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_RequestPRChanges_Call) Return(s string, time1 time.Time, err error) *mockbitbucketClient_RequestPRChanges_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *mockbitbucketClient_RequestPRChanges_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.RequestPRChangesParams) (string, time.Time, error)) *mockbitbucketClient_RequestPRChanges_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePRComment provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) ResolvePRComment(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ResolvePRCommentParams) (*bitbucket.CommentResolution, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePRComment")
	}

	var r0 *bitbucket.CommentResolution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ResolvePRCommentParams) (*bitbucket.CommentResolution, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.ResolvePRCommentParams) *bitbucket.CommentResolution); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.CommentResolution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.ResolvePRCommentParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_ResolvePRComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePRComment'
type mockbitbucketClient_ResolvePRComment_Call struct {
	*mock.Call
}

// ResolvePRComment is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.ResolvePRCommentParams
func (_e *mockbitbucketClient_Expecter) ResolvePRComment(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_ResolvePRComment_Call {
	return &mockbitbucketClient_ResolvePRComment_Call{Call: _e.mock.On("ResolvePRComment", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_ResolvePRComment_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ResolvePRCommentParams)) *mockbitbucketClient_ResolvePRComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.ResolvePRCommentParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.ResolvePRCommentParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_ResolvePRComment_Call) Return(commentResolution *bitbucket.CommentResolution, err error) *mockbitbucketClient_ResolvePRComment_Call {
	_c.Call.Return(commentResolution, err)
	return _c
}

func (_c *mockbitbucketClient_ResolvePRComment_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.ResolvePRCommentParams) (*bitbucket.CommentResolution, error)) *mockbitbucketClient_ResolvePRComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePR provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) UpdatePR(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdatePRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdatePRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdatePRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdatePRParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_UpdatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePR'
type mockbitbucketClient_UpdatePR_Call struct {
	*mock.Call
}

// UpdatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.UpdatePRParams
func (_e *mockbitbucketClient_Expecter) UpdatePR(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_UpdatePR_Call {
	return &mockbitbucketClient_UpdatePR_Call{Call: _e.mock.On("UpdatePR", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_UpdatePR_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdatePRParams)) *mockbitbucketClient_UpdatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.UpdatePRParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.UpdatePRParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_UpdatePR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketClient_UpdatePR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketClient_UpdatePR_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdatePRParams) (*bitbucket.PullRequest, error)) *mockbitbucketClient_UpdatePR_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type mockbitbucketClient
func (_mock *mockbitbucketClient) UpdateTask(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdateTaskParams) (*bitbucket.PullRequestCommentTask, error) {
	ret := _mock.Called(ctx, tokenProvider, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *bitbucket.PullRequestCommentTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdateTaskParams) (*bitbucket.PullRequestCommentTask, error)); ok {
		return returnFunc(ctx, tokenProvider, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdateTaskParams) *bitbucket.PullRequestCommentTask); ok {
		r0 = returnFunc(ctx, tokenProvider, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequestCommentTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bitbucket.TokenProvider, bitbucket.UpdateTaskParams) error); ok {
		r1 = returnFunc(ctx, tokenProvider, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketClient_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type mockbitbucketClient_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenProvider bitbucket.TokenProvider
//   - params bitbucket.UpdateTaskParams
func (_e *mockbitbucketClient_Expecter) UpdateTask(ctx interface{}, tokenProvider interface{}, params interface{}) *mockbitbucketClient_UpdateTask_Call {
	return &mockbitbucketClient_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, tokenProvider, params)}
}

func (_c *mockbitbucketClient_UpdateTask_Call) Run(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdateTaskParams)) *mockbitbucketClient_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bitbucket.TokenProvider
		if args[1] != nil {
			arg1 = args[1].(bitbucket.TokenProvider)
		}
		var arg2 bitbucket.UpdateTaskParams
		if args[2] != nil {
			arg2 = args[2].(bitbucket.UpdateTaskParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockbitbucketClient_UpdateTask_Call) Return(pullRequestCommentTask *bitbucket.PullRequestCommentTask, err error) *mockbitbucketClient_UpdateTask_Call {
	_c.Call.Return(pullRequestCommentTask, err)
	return _c
}

func (_c *mockbitbucketClient_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, tokenProvider bitbucket.TokenProvider, params bitbucket.UpdateTaskParams) (*bitbucket.PullRequestCommentTask, error)) *mockbitbucketClient_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
