// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package controllers

import (
	"context"
	"time"

	"github.com/gemyago/atlacp/internal/app"
	"github.com/gemyago/atlacp/internal/services/bitbucket"
	mock "github.com/stretchr/testify/mock"
)

// newMockbitbucketService creates a new instance of mockbitbucketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbitbucketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbitbucketService {
	mock := &mockbitbucketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbitbucketService is an autogenerated mock type for the bitbucketService type
type mockbitbucketService struct {
	mock.Mock
}

type mockbitbucketService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbitbucketService) EXPECT() *mockbitbucketService_Expecter {
	return &mockbitbucketService_Expecter{mock: &_m.Mock}
}

// AddPRComment provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) AddPRComment(ctx context.Context, params app.BitbucketAddPRCommentParams) (int64, string, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for AddPRComment")
	}

	var r0 int64
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketAddPRCommentParams) (int64, string, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketAddPRCommentParams) int64); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketAddPRCommentParams) string); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, app.BitbucketAddPRCommentParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockbitbucketService_AddPRComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPRComment'
type mockbitbucketService_AddPRComment_Call struct {
	*mock.Call
}

// AddPRComment is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketAddPRCommentParams
func (_e *mockbitbucketService_Expecter) AddPRComment(ctx interface{}, params interface{}) *mockbitbucketService_AddPRComment_Call {
	return &mockbitbucketService_AddPRComment_Call{Call: _e.mock.On("AddPRComment", ctx, params)}
}

func (_c *mockbitbucketService_AddPRComment_Call) Run(run func(ctx context.Context, params app.BitbucketAddPRCommentParams)) *mockbitbucketService_AddPRComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketAddPRCommentParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketAddPRCommentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_AddPRComment_Call) Return(n int64, s string, err error) *mockbitbucketService_AddPRComment_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *mockbitbucketService_AddPRComment_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketAddPRCommentParams) (int64, string, error)) *mockbitbucketService_AddPRComment_Call {
	_c.Call.Return(run)
	return _c
}

// ApprovePR provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) ApprovePR(ctx context.Context, params app.BitbucketApprovePRParams) (*bitbucket.Participant, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ApprovePR")
	}

	var r0 *bitbucket.Participant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketApprovePRParams) (*bitbucket.Participant, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketApprovePRParams) *bitbucket.Participant); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.Participant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketApprovePRParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_ApprovePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApprovePR'
type mockbitbucketService_ApprovePR_Call struct {
	*mock.Call
}

// ApprovePR is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketApprovePRParams
func (_e *mockbitbucketService_Expecter) ApprovePR(ctx interface{}, params interface{}) *mockbitbucketService_ApprovePR_Call {
	return &mockbitbucketService_ApprovePR_Call{Call: _e.mock.On("ApprovePR", ctx, params)}
}

func (_c *mockbitbucketService_ApprovePR_Call) Run(run func(ctx context.Context, params app.BitbucketApprovePRParams)) *mockbitbucketService_ApprovePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketApprovePRParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketApprovePRParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_ApprovePR_Call) Return(participant *bitbucket.Participant, err error) *mockbitbucketService_ApprovePR_Call {
	_c.Call.Return(participant, err)
	return _c
}

func (_c *mockbitbucketService_ApprovePR_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketApprovePRParams) (*bitbucket.Participant, error)) *mockbitbucketService_ApprovePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) CreatePR(ctx context.Context, params app.BitbucketCreatePRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketCreatePRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketCreatePRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketCreatePRParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type mockbitbucketService_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketCreatePRParams
func (_e *mockbitbucketService_Expecter) CreatePR(ctx interface{}, params interface{}) *mockbitbucketService_CreatePR_Call {
	return &mockbitbucketService_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, params)}
}

func (_c *mockbitbucketService_CreatePR_Call) Run(run func(ctx context.Context, params app.BitbucketCreatePRParams)) *mockbitbucketService_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketCreatePRParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketCreatePRParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_CreatePR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketService_CreatePR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketService_CreatePR_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketCreatePRParams) (*bitbucket.PullRequest, error)) *mockbitbucketService_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) CreateTask(ctx context.Context, params app.BitbucketCreateTaskParams) (*bitbucket.PullRequestCommentTask, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *bitbucket.PullRequestCommentTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketCreateTaskParams) (*bitbucket.PullRequestCommentTask, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketCreateTaskParams) *bitbucket.PullRequestCommentTask); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequestCommentTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketCreateTaskParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type mockbitbucketService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketCreateTaskParams
func (_e *mockbitbucketService_Expecter) CreateTask(ctx interface{}, params interface{}) *mockbitbucketService_CreateTask_Call {
	return &mockbitbucketService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, params)}
}

func (_c *mockbitbucketService_CreateTask_Call) Run(run func(ctx context.Context, params app.BitbucketCreateTaskParams)) *mockbitbucketService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketCreateTaskParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketCreateTaskParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_CreateTask_Call) Return(pullRequestCommentTask *bitbucket.PullRequestCommentTask, err error) *mockbitbucketService_CreateTask_Call {
	_c.Call.Return(pullRequestCommentTask, err)
	return _c
}

func (_c *mockbitbucketService_CreateTask_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketCreateTaskParams) (*bitbucket.PullRequestCommentTask, error)) *mockbitbucketService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileContent provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) GetFileContent(ctx context.Context, params app.BitbucketGetFileContentParams) (*bitbucket.FileContentResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContent")
	}

	var r0 *bitbucket.FileContentResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketGetFileContentParams) (*bitbucket.FileContentResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketGetFileContentParams) *bitbucket.FileContentResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.FileContentResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketGetFileContentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_GetFileContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileContent'
type mockbitbucketService_GetFileContent_Call struct {
	*mock.Call
}

// GetFileContent is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketGetFileContentParams
func (_e *mockbitbucketService_Expecter) GetFileContent(ctx interface{}, params interface{}) *mockbitbucketService_GetFileContent_Call {
	return &mockbitbucketService_GetFileContent_Call{Call: _e.mock.On("GetFileContent", ctx, params)}
}

func (_c *mockbitbucketService_GetFileContent_Call) Run(run func(ctx context.Context, params app.BitbucketGetFileContentParams)) *mockbitbucketService_GetFileContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketGetFileContentParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketGetFileContentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_GetFileContent_Call) Return(fileContentResult *bitbucket.FileContentResult, err error) *mockbitbucketService_GetFileContent_Call {
	_c.Call.Return(fileContentResult, err)
	return _c
}

func (_c *mockbitbucketService_GetFileContent_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketGetFileContentParams) (*bitbucket.FileContentResult, error)) *mockbitbucketService_GetFileContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRDiff provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) GetPRDiff(ctx context.Context, params app.BitbucketGetPRDiffParams) (string, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPRDiff")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketGetPRDiffParams) (string, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketGetPRDiffParams) string); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketGetPRDiffParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_GetPRDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRDiff'
type mockbitbucketService_GetPRDiff_Call struct {
	*mock.Call
}

// GetPRDiff is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketGetPRDiffParams
func (_e *mockbitbucketService_Expecter) GetPRDiff(ctx interface{}, params interface{}) *mockbitbucketService_GetPRDiff_Call {
	return &mockbitbucketService_GetPRDiff_Call{Call: _e.mock.On("GetPRDiff", ctx, params)}
}

func (_c *mockbitbucketService_GetPRDiff_Call) Run(run func(ctx context.Context, params app.BitbucketGetPRDiffParams)) *mockbitbucketService_GetPRDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketGetPRDiffParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketGetPRDiffParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_GetPRDiff_Call) Return(s string, err error) *mockbitbucketService_GetPRDiff_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockbitbucketService_GetPRDiff_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketGetPRDiffParams) (string, error)) *mockbitbucketService_GetPRDiff_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRDiffStat provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) GetPRDiffStat(ctx context.Context, params app.BitbucketGetPRDiffStatParams) (*app.PaginatedDiffStat, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPRDiffStat")
	}

	var r0 *app.PaginatedDiffStat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketGetPRDiffStatParams) (*app.PaginatedDiffStat, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketGetPRDiffStatParams) *app.PaginatedDiffStat); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.PaginatedDiffStat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketGetPRDiffStatParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_GetPRDiffStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRDiffStat'
type mockbitbucketService_GetPRDiffStat_Call struct {
	*mock.Call
}

// GetPRDiffStat is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketGetPRDiffStatParams
func (_e *mockbitbucketService_Expecter) GetPRDiffStat(ctx interface{}, params interface{}) *mockbitbucketService_GetPRDiffStat_Call {
	return &mockbitbucketService_GetPRDiffStat_Call{Call: _e.mock.On("GetPRDiffStat", ctx, params)}
}

func (_c *mockbitbucketService_GetPRDiffStat_Call) Run(run func(ctx context.Context, params app.BitbucketGetPRDiffStatParams)) *mockbitbucketService_GetPRDiffStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketGetPRDiffStatParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketGetPRDiffStatParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_GetPRDiffStat_Call) Return(paginatedDiffStat *app.PaginatedDiffStat, err error) *mockbitbucketService_GetPRDiffStat_Call {
	_c.Call.Return(paginatedDiffStat, err)
	return _c
}

func (_c *mockbitbucketService_GetPRDiffStat_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketGetPRDiffStatParams) (*app.PaginatedDiffStat, error)) *mockbitbucketService_GetPRDiffStat_Call {
	_c.Call.Return(run)
	return _c
}

// ListPRComments provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) ListPRComments(ctx context.Context, params app.BitbucketListPRCommentsParams) (*app.BitbucketListPRCommentsResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPRComments")
	}

	var r0 *app.BitbucketListPRCommentsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketListPRCommentsParams) (*app.BitbucketListPRCommentsResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketListPRCommentsParams) *app.BitbucketListPRCommentsResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.BitbucketListPRCommentsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketListPRCommentsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_ListPRComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPRComments'
type mockbitbucketService_ListPRComments_Call struct {
	*mock.Call
}

// ListPRComments is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketListPRCommentsParams
func (_e *mockbitbucketService_Expecter) ListPRComments(ctx interface{}, params interface{}) *mockbitbucketService_ListPRComments_Call {
	return &mockbitbucketService_ListPRComments_Call{Call: _e.mock.On("ListPRComments", ctx, params)}
}

func (_c *mockbitbucketService_ListPRComments_Call) Run(run func(ctx context.Context, params app.BitbucketListPRCommentsParams)) *mockbitbucketService_ListPRComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketListPRCommentsParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketListPRCommentsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_ListPRComments_Call) Return(bitbucketListPRCommentsResult *app.BitbucketListPRCommentsResult, err error) *mockbitbucketService_ListPRComments_Call {
	_c.Call.Return(bitbucketListPRCommentsResult, err)
	return _c
}

func (_c *mockbitbucketService_ListPRComments_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketListPRCommentsParams) (*app.BitbucketListPRCommentsResult, error)) *mockbitbucketService_ListPRComments_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) ListTasks(ctx context.Context, params app.BitbucketListTasksParams) (*bitbucket.PaginatedTasks, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 *bitbucket.PaginatedTasks
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketListTasksParams) (*bitbucket.PaginatedTasks, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketListTasksParams) *bitbucket.PaginatedTasks); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PaginatedTasks)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketListTasksParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type mockbitbucketService_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketListTasksParams
func (_e *mockbitbucketService_Expecter) ListTasks(ctx interface{}, params interface{}) *mockbitbucketService_ListTasks_Call {
	return &mockbitbucketService_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, params)}
}

func (_c *mockbitbucketService_ListTasks_Call) Run(run func(ctx context.Context, params app.BitbucketListTasksParams)) *mockbitbucketService_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketListTasksParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketListTasksParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_ListTasks_Call) Return(paginatedTasks *bitbucket.PaginatedTasks, err error) *mockbitbucketService_ListTasks_Call {
	_c.Call.Return(paginatedTasks, err)
	return _c
}

func (_c *mockbitbucketService_ListTasks_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketListTasksParams) (*bitbucket.PaginatedTasks, error)) *mockbitbucketService_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) MergePR(ctx context.Context, params app.BitbucketMergePRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketMergePRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketMergePRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketMergePRParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type mockbitbucketService_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketMergePRParams
func (_e *mockbitbucketService_Expecter) MergePR(ctx interface{}, params interface{}) *mockbitbucketService_MergePR_Call {
	return &mockbitbucketService_MergePR_Call{Call: _e.mock.On("MergePR", ctx, params)}
}

func (_c *mockbitbucketService_MergePR_Call) Run(run func(ctx context.Context, params app.BitbucketMergePRParams)) *mockbitbucketService_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketMergePRParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketMergePRParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_MergePR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketService_MergePR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketService_MergePR_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketMergePRParams) (*bitbucket.PullRequest, error)) *mockbitbucketService_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// ReadPR provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) ReadPR(ctx context.Context, params app.BitbucketReadPRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ReadPR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketReadPRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketReadPRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketReadPRParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_ReadPR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadPR'
type mockbitbucketService_ReadPR_Call struct {
	*mock.Call
}

// ReadPR is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketReadPRParams
func (_e *mockbitbucketService_Expecter) ReadPR(ctx interface{}, params interface{}) *mockbitbucketService_ReadPR_Call {
	return &mockbitbucketService_ReadPR_Call{Call: _e.mock.On("ReadPR", ctx, params)}
}

func (_c *mockbitbucketService_ReadPR_Call) Run(run func(ctx context.Context, params app.BitbucketReadPRParams)) *mockbitbucketService_ReadPR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketReadPRParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketReadPRParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_ReadPR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketService_ReadPR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketService_ReadPR_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketReadPRParams) (*bitbucket.PullRequest, error)) *mockbitbucketService_ReadPR_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPRChanges provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) RequestPRChanges(ctx context.Context, params app.BitbucketRequestPRChangesParams) (string, time.Time, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RequestPRChanges")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketRequestPRChangesParams) (string, time.Time, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketRequestPRChangesParams) string); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketRequestPRChangesParams) time.Time); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, app.BitbucketRequestPRChangesParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockbitbucketService_RequestPRChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPRChanges'
type mockbitbucketService_RequestPRChanges_Call struct {
	*mock.Call
}

// RequestPRChanges is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketRequestPRChangesParams
func (_e *mockbitbucketService_Expecter) RequestPRChanges(ctx interface{}, params interface{}) *mockbitbucketService_RequestPRChanges_Call {
	return &mockbitbucketService_RequestPRChanges_Call{Call: _e.mock.On("RequestPRChanges", ctx, params)}
}

func (_c *mockbitbucketService_RequestPRChanges_Call) Run(run func(ctx context.Context, params app.BitbucketRequestPRChangesParams)) *mockbitbucketService_RequestPRChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketRequestPRChangesParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketRequestPRChangesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_RequestPRChanges_Call) Return(s string, time1 time.Time, err error) *mockbitbucketService_RequestPRChanges_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *mockbitbucketService_RequestPRChanges_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketRequestPRChangesParams) (string, time.Time, error)) *mockbitbucketService_RequestPRChanges_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePRComment provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) ResolvePRComment(ctx context.Context, params app.BitbucketResolvePRCommentParams) (*bitbucket.CommentResolution, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePRComment")
	}

	var r0 *bitbucket.CommentResolution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketResolvePRCommentParams) (*bitbucket.CommentResolution, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketResolvePRCommentParams) *bitbucket.CommentResolution); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.CommentResolution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketResolvePRCommentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_ResolvePRComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePRComment'
type mockbitbucketService_ResolvePRComment_Call struct {
	*mock.Call
}

// ResolvePRComment is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketResolvePRCommentParams
func (_e *mockbitbucketService_Expecter) ResolvePRComment(ctx interface{}, params interface{}) *mockbitbucketService_ResolvePRComment_Call {
	return &mockbitbucketService_ResolvePRComment_Call{Call: _e.mock.On("ResolvePRComment", ctx, params)}
}

func (_c *mockbitbucketService_ResolvePRComment_Call) Run(run func(ctx context.Context, params app.BitbucketResolvePRCommentParams)) *mockbitbucketService_ResolvePRComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketResolvePRCommentParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketResolvePRCommentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_ResolvePRComment_Call) Return(commentResolution *bitbucket.CommentResolution, err error) *mockbitbucketService_ResolvePRComment_Call {
	_c.Call.Return(commentResolution, err)
	return _c
}

func (_c *mockbitbucketService_ResolvePRComment_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketResolvePRCommentParams) (*bitbucket.CommentResolution, error)) *mockbitbucketService_ResolvePRComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePR provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) UpdatePR(ctx context.Context, params app.BitbucketUpdatePRParams) (*bitbucket.PullRequest, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePR")
	}

	var r0 *bitbucket.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketUpdatePRParams) (*bitbucket.PullRequest, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketUpdatePRParams) *bitbucket.PullRequest); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketUpdatePRParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_UpdatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePR'
type mockbitbucketService_UpdatePR_Call struct {
	*mock.Call
}

// UpdatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketUpdatePRParams
func (_e *mockbitbucketService_Expecter) UpdatePR(ctx interface{}, params interface{}) *mockbitbucketService_UpdatePR_Call {
	return &mockbitbucketService_UpdatePR_Call{Call: _e.mock.On("UpdatePR", ctx, params)}
}

func (_c *mockbitbucketService_UpdatePR_Call) Run(run func(ctx context.Context, params app.BitbucketUpdatePRParams)) *mockbitbucketService_UpdatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketUpdatePRParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketUpdatePRParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_UpdatePR_Call) Return(pullRequest *bitbucket.PullRequest, err error) *mockbitbucketService_UpdatePR_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *mockbitbucketService_UpdatePR_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketUpdatePRParams) (*bitbucket.PullRequest, error)) *mockbitbucketService_UpdatePR_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type mockbitbucketService
func (_mock *mockbitbucketService) UpdateTask(ctx context.Context, params app.BitbucketUpdateTaskParams) (*bitbucket.PullRequestCommentTask, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *bitbucket.PullRequestCommentTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketUpdateTaskParams) (*bitbucket.PullRequestCommentTask, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.BitbucketUpdateTaskParams) *bitbucket.PullRequestCommentTask); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.PullRequestCommentTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.BitbucketUpdateTaskParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbitbucketService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type mockbitbucketService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - params app.BitbucketUpdateTaskParams
func (_e *mockbitbucketService_Expecter) UpdateTask(ctx interface{}, params interface{}) *mockbitbucketService_UpdateTask_Call {
	return &mockbitbucketService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, params)}
}

func (_c *mockbitbucketService_UpdateTask_Call) Run(run func(ctx context.Context, params app.BitbucketUpdateTaskParams)) *mockbitbucketService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.BitbucketUpdateTaskParams
		if args[1] != nil {
			arg1 = args[1].(app.BitbucketUpdateTaskParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbitbucketService_UpdateTask_Call) Return(pullRequestCommentTask *bitbucket.PullRequestCommentTask, err error) *mockbitbucketService_UpdateTask_Call {
	_c.Call.Return(pullRequestCommentTask, err)
	return _c
}

func (_c *mockbitbucketService_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, params app.BitbucketUpdateTaskParams) (*bitbucket.PullRequestCommentTask, error)) *mockbitbucketService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
